# This is a basic workflow to help you get started with Actions

name: UPDATE json files daily

# Controls when the workflow will run
on:
  schedule:
  - cron: "30 21 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-by:
    uses: zubrabubra/pl-decisions-tracker.github.io/.github/workflows/country_data.yml@main
    with:
      country: 'BY'
  get-ru:
    needs: get-by
    uses: zubrabubra/pl-decisions-tracker.github.io/.github/workflows/country_data.yml@main
    with:
      country: 'RU'


